server:
  port: 8081
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configuration:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: empleado-service
          uri: http://empleado-service:8080
          predicates:
            - Path=/empleado/** 
        - id: hora-extra-service
          uri: http://hora-extra-service:8084
          predicates:
            - Path=/hora-extra/**   
        - id: inasistencia-service
          uri: http://inasistencia-service:8085
          predicates:
            - Path=/inasistencia/** 
        - id: marca-entrada-salida-service
          uri: http://marca-entrada-salida-service:8086
          predicates:
            - Path=/marca-entrada-salida/** 
        - id: planilla-sueldo-service
          uri: http://planilla-sueldo-service:8087
          predicates:
            - Path=/planilla-sueldo/** 
